SELECT ID, IFNULL(C.COUNT_CHILD,0) AS CHILD_COUNT
FROM ECOLI_DATA AS E LEFT JOIN(
SELECT PARENT_ID,COUNT(*)AS COUNT_CHILD
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID)AS C ON E.ID = C.PARENT_ID
ORDER BY ID

