SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM ONLINE_SALE
    UNION ALL
    SELECT OFFLINE_SALE_ID,  NULL AS USER_ID,PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE
    )AS SALES_DATA
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
ORDER BY SALES_DATE ASC, PRODUCT_ID, USER_ID

