-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
     FROM REST_INFO
     GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC)S
ON R.FOOD_TYPE = S.FOOD_TYPE AND R.FAVORITES = S.FAVORITES
ORDER BY FOOD_TYPE DESC