SELECT H.CAR_ID,
       CASE WHEN SUM(CASE WHEN '2022-10-16' BETWEEN H.START_DATE AND H.END_DATE 
                          THEN 1 ELSE 0 END) = 1 THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
 GROUP BY H.CAR_ID
 ORDER BY H.CAR_ID DESC;