-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT*A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A RIGHT JOIN FOOD_ORDER B USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')  =  '2022-05'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

