SELECT H.FLAVOR
FROM 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_FIRST_HALF
     FROM FIRST_HALF
     GROUP BY FLAVOR) AS H
JOIN 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_JULY
     FROM JULY
     GROUP BY FLAVOR) AS J
ON H.FLAVOR = J.FLAVOR
ORDER BY (H.SUM_FIRST_HALF + J.SUM_JULY) DESC
LIMIT 3;
