WITH FRONT AS(SELECT SUM(CODE) AS FC FROM SKILLCODES WHERE CATEGORY ='Front End'),
 PYTHON AS (SELECT CODE AS PC FROM SKILLCODES WHERE NAME = 'Python'),
CS AS (SELECT CODE AS CSS FROM SKILLCODES WHERE NAME = 'C#')

SELECT 
    CASE 
        WHEN SKILL_CODE & FC!=0 AND SKILL_CODE &PC!=0 THEN 'A'
        WHEN SKILL_CODE & CSS!=0 THEN 'B'
        WHEN SKILL_CODE & FC!=0 THEN 'C'
    END AS GRADE
    , ID, EMAIL
FROM DEVELOPERS
CROSS JOIN FRONT
CROSS JOIN PYTHON
CROSS JOIN CS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID ASC
